version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env           # ✅ Loads app + DB env vars
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env           # ✅ Loads from the same .env file
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
